apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hysx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hysx
    app.kubernetes.io/part-of: valentines-day-test
  name: devfile-sample-hysx
  namespace: afred-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-hysx
status:
  loadBalancer: {}
